FROM arm32v7/alpine
LABEL "project"="www.mf2c-project.eu" "status"="production" "maintainer"="jens.jensen@stfc.ac.uk"

# This file is for the production mf2c/vpnclient images
# However, we still include curl, even if it should not be needed.

RUN apk add --no-cache openvpn openssl curl
ENV VPN_DAEMON=FALSE
ADD vpnclient.sh "/root/vpnclient.sh"
# Alpine doesn't have bash (by default) and the script only needs sh
CMD ["sh", "/root/vpnclient.sh"]
